### ISSUE TITLE
Add images for wiki here :)

### ISSUE THREAD

**Issue by btsimonh** [bipropellant/hoverboard-firmware#4]
![hbsmall](https://user-images.githubusercontent.com/3137332/56945320-b9afae00-6b1e-11e9-8610-7d587d70132d.jpg)

**Comment by btsimonh** [comment]
![image](https://user-images.githubusercontent.com/3137332/59148928-b73a5100-8a06-11e9-8857-18d6996b7511.png)

**Comment by btsimonh** [comment]
![image](https://user-images.githubusercontent.com/3137332/59148951-19935180-8a07-11e9-994f-b2eadaaa8e66.png)

**Comment by btsimonh** [comment]
![image](https://user-images.githubusercontent.com/3137332/59148965-48a9c300-8a07-11e9-8fef-45722f7ef796.png)

**Comment by btsimonh** [comment]
![image](https://user-images.githubusercontent.com/3137332/59149010-d84f7180-8a07-11e9-80d6-f17b93fa441e.png)

**Comment by btsimonh** [comment]
![image](https://user-images.githubusercontent.com/3137332/59149033-1cdb0d00-8a08-11e9-92a7-aa06c92c5e90.png)

**Comment by btsimonh** [comment]
Pictures used in the wiki Projects/btsimonh page :).

**Comment by AntumArk** [comment]
![IMG_20190708_154703](https://user-images.githubusercontent.com/23199497/60812546-6dc25a80-a19a-11e9-95c1-cf16f404b8ca.jpg)
