### ISSUE TITLE
sideboard protocol

### ISSUE THREAD

**Issue by fallenfallen** [bipropellant/hoverboard-firmware#7]
Could you describe the communication protocol with the gyroscope board?

**Comment by btsimonh** [comment]
look [here](https://github.com/btsimonh/hoverboard-firmware-hack/blob/newprotocol/otherboards/YST-6.5-10-PCBA-10/originalfirmwareanalysis.md) and at sensorcoms.c

Bear in mind it's running in 9 bit mode - you must have an MCU which supports this to sync to the protocol, although you could get somewhere close with pattern matching the duplicated bytes.

s

**Comment by fallenfallen** [comment]
Thanks!
